create database if not exists SQLbasics;
-- If Database already exists then it will give warning

USE SQLBASICS;
CREATE TABLE STUDENT(NAME VARCHAR(50),ROLL_NO INT(10),ADDRESS VARCHAR(30));

INSERT INTO STUDENT_INFO
VALUES("GANESH",2010030,"KOLHAPUR",22),
("VIKAS",2010034,"KAGAL",21),
("UTTAM",2030400,"PUNE",30);

DESCRIBE STUDENT;
-- It is used to describe the whole table like which datatype is used,keys used, null values,default values,etc


-- THE BELOW QUERY IS OK BEACAUSE WE HAVE USED ONLY SPECIFIC COLUMNS NAME
INSERT INTO STUDENT(NAME,ROLL_NO)
VALUE("NJK",2030420);

-- IF WE DONT KNOW ANY VALUE THEN WE CAN MAKE THAT VALUE AS NULL COMPULSORY SO THAT WE CAN MODIFY IT IN FUTURE
INSERT INTO STUDENT
VALUE("FRBGNK",2030420,NULL);


SELECT NAME FIRST_NAME,ROLL_NO PRN 
FROM STUDENT;

TRUNCATE TABLE STUDENT_INFO; 

RENAME TABLE STUDENT TO STUDENT_INFO;

ALTER TABLE STUDENT_INFO
ADD AGE INT(10);

ALTER TABLE STUDENT_INFO
RENAME COLUMN ADDRESS TO STUD_ADDRESS;

DESC STUDENT_INFO;

INSERT INTO STUDENT_INFO
VALUES("VIGNESH",2010030,"KOLHAPUR"),
("VIKI",2010034,"KOLHAPUR"),
("UTTI",2030400,"KOLHAPUR");
 
SELECT DISTINCT COUNT( sTUD_ADDRESS) 
FROM STUDENT_INFO;

UPDATE STUDENT_INFO
SET STUD_AdDRESS='MUMBAI'
WHERE NAME='VIGNESH';

SELECT * FROM STUDENT_INFO;
SET SQL_SAFE_UPDATES = 0;

DELETE FROM STUDENT_INFO
WHERE STUD_ADDRESS='PUNE';


-- CLAUSES
-- 1) OEDER BY

SELECT * FROM STUDENT_INFO 
ORDER BY NAME;

INSERT INTO STUDENT_INFO
VALUE('DHANRAJ',NULL,'YEVLUJ');


-- IS NULL
SELECT * FROM STUDENT_INFO 
WHERE ROLL_NO IS NULL;

-- IS NOT NULL
SELECT * FROM STUDENT_INFO 
WHERE ROLL_NO IS NOT NULL;